[General]
SyntaxVersion=2
BeginHotkey=88
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=107
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=f638aa0b-b6e0-4af7-a926-22497904cb23
Description=GGGGGGGGGGG
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "g",1
//KeyDownH "w", 1
KeyDownH "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
