[General]
SyntaxVersion=2
BeginHotkey=88
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=107
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=6c13cffb-8c13-47e3-8b89-ae2a5b4bd855
Description=WWWWWWWWWWWWWWWWWWWWWW
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "w",1
KeyDownH "w", 1
///KeyDownH "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
