[General]
SyntaxVersion=2
BeginHotkey=32
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=da54380e-72b9-48af-acc7-b2dc7430180c
Description=nico ssaqkuest
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "s", 1
Delay 50
KeyDown "s", 1
KeyDown "a", 1
Delay 50
KeyUp "s", 1

KeyDown "k", 1
Delay 400
KeyUp "a", 1
Delay 50
keyup"k",1
