[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=d6d0426f-defd-446c-8187-d86cd96b8fb6
Description=恶心人的玩意还COBO THROW
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]

KeyDown "s", 1
Delay 100 
KeyDown "d", 1
KeyUp "s", 1
Delay 100
KeyPress "m", 1
KeyUp "d", 1
Delay 1400
KeyPress"m",1
