[General]
SyntaxVersion=2
BeginHotkey=66
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=32782
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=a9ce33de-edce-4fc9-b60e-f2d13812f21b
Description=WWWWWWWWWWWWWWWWWWWWWW
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "w",1
KeyDownS "w", 1
///KeyDownH "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
