[General]
SyntaxVersion=2
BeginHotkey=88
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=32781
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=e96abb4d-d83b-485d-8e08-e45f9a79b683
Description=GGGGGGGGGGG
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "g",1
//KeyDownH "w", 1
KeyDownS "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
