[General]
SyntaxVersion=2
BeginHotkey=112
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=90
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=344f4708-e9f3-47f4-aa45-f4bbfc5eeea4
Description=WWWWWWWWWWWWWWWWWWWWWW
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "w",1
KeyDownS "w", 1
///KeyDownH "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
