[General]
SyntaxVersion=2
BeginHotkey=192
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=88
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=22ea534c-c433-4560-9341-19e0ebbbc872
Description=GGGGGGGGGGG
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While true

//KeyPressH "g",1
//KeyDownH "w", 1
KeyDownS "g", 1
//KeyUpH "g",1
//KeyUpH "w",1
Wend
