[General]
SyntaxVersion=2
BeginHotkey=70
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=24eaad63-2854-4b9d-8448-2066af058f9a
Description=ÍÆÍÆ4¹×²Ä2R¿ì½ÝF
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "4", 2
Delay  600
KeyDown "r", 1
KeyDown "2", 1
KeyUp "2", 1
KeyUp "r", 1
