[General]
SyntaxVersion=2
BeginHotkey=68
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=e8db1c6d-93f6-47e9-999d-e7b072f85c12
Description=鼠标释放技能
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "q",1
MoveTo 887,918
Delay 1
LeftClick 1
/*834,927
887,918
941,919
996,920*/
