[General]
SyntaxVersion=2
BeginHotkey=122
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=bdf14db6-9b76-4ee0-875a-5435a4ee92aa
Description=À­´ó
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]

MoveTo 1000, 42
Delay 30
LeftDown 1
Delay 30
MoveTo l030,0
Delay 30
LeftUp 1
Delay 30
MoveTo 904, 988
Delay 30
LeftDown 1
Delay 30
MoveTo 982, 1029
Delay 30
LeftUp 1
