[General]
SyntaxVersion=2
BeginHotkey=107
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=86584c1d-0f3b-40df-9cc6-6237c61e7d31
Description=Íò»ª¾µÒ»
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
Delay 50
MoveTo 970, 373
Delay 50
LeftClick 1
Delay 100
MoveTo 996, 968
Delay 200
LeftClick 1
Delay 200
LeftClick 1
Delay 100
MoveTo 970, 373
Delay 50
LeftClick 1

