[General]
SyntaxVersion=2
BeginHotkey=107
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=c8a993a8-f0f5-4372-a073-00abdeea2aad
Description=Õ‚√Êµ„
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
Delay 50
MoveTo 970, 373
LeftClick 1

MoveTo 996, 888 //in vitual
LeftClick 1
Delay 100
LeftClick 1
Delay 100
LeftClick 1
Delay 100
