[General]
SyntaxVersion=2
BeginHotkey=107
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=e5038271-015b-4d86-b8c8-f1766334c4da
Description=万华镜一改
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
Delay 50
MoveTo 970, 373
Delay 100
LeftClick 1
Delay 200
LeftClick 1
Delay 100
MoveTo 996, 968
Delay 200
LeftClick 1
Delay 200
LeftClick 1
Delay 100
MoveTo 58,312




