[General]
SyntaxVersion=2
BeginHotkey=120
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=8715381c-1351-4fb8-b8e8-aba83b45d548
Description=∏Ù¡„µ„∂˛√Î∫∞ª∞£®ºÙ«–∞Â
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
While 1

Delay 200

KeyPress "enter", 1
Delay  60
KeyDown "ctrl", 1
Delay 30
KeyPress "v", 1
KeyUp "ctrl",1
Delay 60

KeyPress "enter", 1
Wend
